Mellanox/nvidia-k8s-ipam

- deploy/nv-ipam.yaml
Remove hostNetwork from nv-ipam-node
Add args to easy change log level in nv-ipam-node
Remove kube- prefix
> minor changes to nv-ipam.yaml

- .github/workflows/build-test-lint.yml
- .gitignore
- Makefile
- update Makefile
- add GitHub action for report uploading
> Add support for coverage report

- .dockerignore
- .gitignore
i. add `vendor/` dir to gitignored files. I use `go mod vendor` to build and compile programs locally.
ii. add `.dockerignore` as best practice
> add .dockerignore file

- cmd/ipam-controller/app/app_suite_test.go
- cmd/ipam-controller/app/app_test.go
- pkg/ipam-controller/allocator/allocator.go
Test data loading logic in the controller by
setting annotations with valid and invalid
data for nodes before the controller starts.
++ improve logging for allocator package
> Improve  tests for IPAM controller

- CONTRIBUTING.md
- README.md
- Update README
- Add CONTRIBUTING doc
> Add Documentation

- README.md
- cmd/ipam-controller/app/app.go
- cmd/ipam-controller/app/options/options.go
- deploy/nv-ipam.yaml
By default, the leader election is now enabled in the deployment yaml
but controller's replica count is set to 1.
This is required to prevent IPAM controller
misbehavior in case if user will decide to scale the deployment.
> Add support for leader election

- cmd/ipam-node/app/app.go
- pkg/ipam-node/cleaner/cleaner.go
- pkg/ipam-node/cleaner/cleaner_test.go
- pkg/ipam-node/store/mocks/Session.go
- pkg/ipam-node/store/store.go
- pkg/ipam-node/store/store_test.go
remove the pool data from the store if the pool has no allocations and if information about the pool is unavailable in the Kubernetes API
closes #25
> ipam-node: Remove stale pool entries from the store

- deploy/nv-ipam.yaml
This required to avoid problems with RollingUpdate on the single node cluster.
With the current affinity rule new pod instance will stuck in the pending state and this will block ipam-controller update.
network-operator already uses the right affinity rule, so the problem exist only in this repo.
> Use "preferred" podAntiAffinity instead of "required" for controller pod

- cmd/ipam-node/app/app.go
- pkg/ipam-node/migrator/migrator.go
- pkg/ipam-node/migrator/migrator_suite_test.go
- pkg/ipam-node/migrator/migrator_test.go
This required to preserve IP reservations which were done by the previous version of the nv-ipam.
> ipam-node: Add logic to migrate host-local IPAM store to the new store format

- cmd/ipam-controller/app/app.go
- cmd/ipam-controller/app/app_test.go
- pkg/ipam-controller/controllers/ippool/ippool.go
- pkg/ipam-controller/controllers/node/node.go
- pkg/ipam-controller/migrator/migrator.go
- pkg/ipam-controller/migrator/migrator_test.go
- Add Controller Migrator to the Manager
- Add a channel to block reconcile until Migrator finishes
> Run migration logic with leader election

- README.md
- examples/ippool-1.yaml
- examples/ippool-2.yaml
Replace `kubernetes.io/role` label with
`node-role.kubernetes.io/worker` which is more common
> Fix label selector in examples for IPPool CR

- README.md
- examples/ippool-2.yaml
Add IPv6 examples to README.md and fix pool
name in existing examples
> Add IPv6 pool example to README.md

- cmd/ipam-node/app/app.go
- go.mod
- pkg/ipam-node/cleaner/cleaner.go
- pkg/ipam-node/cleaner/cleaner_suite_test.go
- pkg/ipam-node/cleaner/cleaner_test.go
Before the fix,  nv-ipam-node was watching only for Pods in the namespace provided by `-- ippools-namespace` arg. This is incorrect and cause "stale IP cleaner" to work incorrectly.
Watch Pods in all namespaces instead.
\+ Add extra check to the cleaner to check Pod in the API (in addition to the cache)
before decide to cleanup the stale allocation.
> Fix pod watch namespace for nv-ipam-node

- README.md
- docs/extra-cni-args.md
- docs/static-ip.md
The PR contains documentation for features introduced in #45
> Add documentation for static IP and extra CNI args

- api/v1alpha1/cidrpool_test.go
- api/v1alpha1/cidrpool_type.go
- api/v1alpha1/cidrpool_validate.go
- api/v1alpha1/helpers.go
- api/v1alpha1/helpers_test.go
- api/v1alpha1/zz_generated.deepcopy.go
- cmd/ipam-controller/app/app_test.go
- cmd/ipam-node/app/app_test.go
- deploy/crds/nv-ipam.nvidia.com_cidrpools.yaml
- go.mod
- pkg/ip/cidr.go
According to the [API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types), we should not use `uint` type for fields. 
> * All public integer fields MUST use the Go int32 or Go int64 types, not int (which is ambiguously sized, depending on target platform). Internal types may use int.
> * Do not use unsigned integers, due to inconsistent support across languages and libraries. Just validate that the integer is non-negative if that's the case. 
In fact, issues using `uint` can also be observed when trying to `DeepCopyJSON` the object that panics with error `panic: cannot deep copy uint64`. (e.g. convert the object to `unstructured.Unstructured` and then call `unstructuredObj.DeepCopy()`)
Upstream issue: …
> Adjust CIDRPool to use int32 instead of uint fields

- docs/extra-cni-args.md
The correct name is "poolNames"
> fix: CNI arg name in the example in extra-cni-args.md

- Dockerfile
- README.md
- cmd/ipam-node/app/app.go
- cmd/ipam-node/app/app_test.go
- cmd/ipam-node/app/options/options.go
- pkg/cni/types/types.go
- pkg/cni/types/types_test.go
in some cases it is desired to make specifying at least one pool in poolName or pools mandatory. To achieve this we add a new IPAM CNI parameter which can be defined in nv-ipam config file. this will prevent CNI from using network name as pool name in case poolName was not specified.
> Add option to force specifying pool name

- README.md
The `--cni-force-pool-name` is a flag, not a string parameter
> Fix `--cni-force-pool-name` param description in README.md

- README.md
The typo was already fixed in the API, updated the README.md to use the correct field name
> Fix: change 'defautGateway' to 'defaultGateway' in README.md

- README.md
- api/v1alpha1/cidrpool_test.go
- api/v1alpha1/cidrpool_validate.go
- api/v1alpha1/ippool_validate.go
- pkg/ip/cidr.go
- pkg/ip/cidr_test.go
- pkg/ipam-controller/allocator/allocator.go
- pkg/ipam-controller/allocator/allocator_test.go
- pkg/ipam-controller/config/config_test.go
- pkg/ipam-node/allocator/allocator_test.go
- pkg/ipam-node/allocator/range.go
- pkg/ipam-node/allocator/range_test.go
- pkg/ipam-node/controllers/cidrpool/cidrpool.go
- pkg/ipam-node/controllers/cidrpool/cidrpool_test.go
Add support for single IP ranges/subnets in all places:
<details>
<summary>IPPool perNodeBlockSize 1</summary>
```
apiVersion: nv-ipam.nvidia.com/v1alpha1
kind: IPPool
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"nv-ipam.nvidia.com/v1alpha1","kind":"IPPool","metadata":{"annotations":{},"name":"pool1","namespace":"kube-system"},"spec":{"gateway":"192.168.0.3","perNodeBlockSize":1,"subnet":"192.168.0.0/24"}}
creationTimestamp: "2024-10-14T16:44:59Z"
generation: 15
name: pool1
namespace: kube-system
resourceVersion: "16150"
uid: b43c059a-9364-4fbc-b945-1a1f017ddb1b
spec:
gateway: 192.168.0.3
perNodeBlockSize: 1
subnet: 192.168.0.0/24
status:
allocations:
- endIP: 192.168.0.2
nodeName: kind-control-plane
startIP: 192.168.0.2
- endIP: 192.168.0.1 …
```
> Add support for /32 (/128) networks and perNodeBlockSize 1
